services:
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}

  db:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: wafer
      POSTGRES_PASSWORD: wafer
      POSTGRES_DB: wafer_dev
    volumes:
      - wafer_postgres_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  wafer_postgres_db:
